// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Article is the predicate function for article builders.
type Article func(*sql.Selector)

// Column is the predicate function for column builders.
type Column func(*sql.Selector)

// Newspaper is the predicate function for newspaper builders.
type Newspaper func(*sql.Selector)
