// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/jijimama/newspaper-app/ent/article"
	"github.com/jijimama/newspaper-app/ent/newspaper"
	"github.com/jijimama/newspaper-app/ent/predicate"
)

// ArticleUpdate is the builder for updating Article entities.
type ArticleUpdate struct {
	config
	hooks    []Hook
	mutation *ArticleMutation
}

// Where appends a list predicates to the ArticleUpdate builder.
func (au *ArticleUpdate) Where(ps ...predicate.Article) *ArticleUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetContent sets the "content" field.
func (au *ArticleUpdate) SetContent(s string) *ArticleUpdate {
	au.mutation.SetContent(s)
	return au
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableContent(s *string) *ArticleUpdate {
	if s != nil {
		au.SetContent(*s)
	}
	return au
}

// SetYear sets the "year" field.
func (au *ArticleUpdate) SetYear(i int) *ArticleUpdate {
	au.mutation.ResetYear()
	au.mutation.SetYear(i)
	return au
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableYear(i *int) *ArticleUpdate {
	if i != nil {
		au.SetYear(*i)
	}
	return au
}

// AddYear adds i to the "year" field.
func (au *ArticleUpdate) AddYear(i int) *ArticleUpdate {
	au.mutation.AddYear(i)
	return au
}

// SetMonth sets the "month" field.
func (au *ArticleUpdate) SetMonth(i int) *ArticleUpdate {
	au.mutation.ResetMonth()
	au.mutation.SetMonth(i)
	return au
}

// SetNillableMonth sets the "month" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableMonth(i *int) *ArticleUpdate {
	if i != nil {
		au.SetMonth(*i)
	}
	return au
}

// AddMonth adds i to the "month" field.
func (au *ArticleUpdate) AddMonth(i int) *ArticleUpdate {
	au.mutation.AddMonth(i)
	return au
}

// SetDay sets the "day" field.
func (au *ArticleUpdate) SetDay(i int) *ArticleUpdate {
	au.mutation.ResetDay()
	au.mutation.SetDay(i)
	return au
}

// SetNillableDay sets the "day" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableDay(i *int) *ArticleUpdate {
	if i != nil {
		au.SetDay(*i)
	}
	return au
}

// AddDay adds i to the "day" field.
func (au *ArticleUpdate) AddDay(i int) *ArticleUpdate {
	au.mutation.AddDay(i)
	return au
}

// SetCreatedAt sets the "created_at" field.
func (au *ArticleUpdate) SetCreatedAt(t time.Time) *ArticleUpdate {
	au.mutation.SetCreatedAt(t)
	return au
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (au *ArticleUpdate) SetNillableCreatedAt(t *time.Time) *ArticleUpdate {
	if t != nil {
		au.SetCreatedAt(*t)
	}
	return au
}

// SetUpdatedAt sets the "updated_at" field.
func (au *ArticleUpdate) SetUpdatedAt(t time.Time) *ArticleUpdate {
	au.mutation.SetUpdatedAt(t)
	return au
}

// SetNewspaperID sets the "newspaper" edge to the Newspaper entity by ID.
func (au *ArticleUpdate) SetNewspaperID(id int) *ArticleUpdate {
	au.mutation.SetNewspaperID(id)
	return au
}

// SetNillableNewspaperID sets the "newspaper" edge to the Newspaper entity by ID if the given value is not nil.
func (au *ArticleUpdate) SetNillableNewspaperID(id *int) *ArticleUpdate {
	if id != nil {
		au = au.SetNewspaperID(*id)
	}
	return au
}

// SetNewspaper sets the "newspaper" edge to the Newspaper entity.
func (au *ArticleUpdate) SetNewspaper(n *Newspaper) *ArticleUpdate {
	return au.SetNewspaperID(n.ID)
}

// Mutation returns the ArticleMutation object of the builder.
func (au *ArticleUpdate) Mutation() *ArticleMutation {
	return au.mutation
}

// ClearNewspaper clears the "newspaper" edge to the Newspaper entity.
func (au *ArticleUpdate) ClearNewspaper() *ArticleUpdate {
	au.mutation.ClearNewspaper()
	return au
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *ArticleUpdate) Save(ctx context.Context) (int, error) {
	au.defaults()
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *ArticleUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *ArticleUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *ArticleUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (au *ArticleUpdate) defaults() {
	if _, ok := au.mutation.UpdatedAt(); !ok {
		v := article.UpdateDefaultUpdatedAt()
		au.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *ArticleUpdate) check() error {
	if v, ok := au.mutation.Content(); ok {
		if err := article.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Article.content": %w`, err)}
		}
	}
	if v, ok := au.mutation.Year(); ok {
		if err := article.YearValidator(v); err != nil {
			return &ValidationError{Name: "year", err: fmt.Errorf(`ent: validator failed for field "Article.year": %w`, err)}
		}
	}
	if v, ok := au.mutation.Month(); ok {
		if err := article.MonthValidator(v); err != nil {
			return &ValidationError{Name: "month", err: fmt.Errorf(`ent: validator failed for field "Article.month": %w`, err)}
		}
	}
	if v, ok := au.mutation.Day(); ok {
		if err := article.DayValidator(v); err != nil {
			return &ValidationError{Name: "day", err: fmt.Errorf(`ent: validator failed for field "Article.day": %w`, err)}
		}
	}
	return nil
}

func (au *ArticleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(article.Table, article.Columns, sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Content(); ok {
		_spec.SetField(article.FieldContent, field.TypeString, value)
	}
	if value, ok := au.mutation.Year(); ok {
		_spec.SetField(article.FieldYear, field.TypeInt, value)
	}
	if value, ok := au.mutation.AddedYear(); ok {
		_spec.AddField(article.FieldYear, field.TypeInt, value)
	}
	if value, ok := au.mutation.Month(); ok {
		_spec.SetField(article.FieldMonth, field.TypeInt, value)
	}
	if value, ok := au.mutation.AddedMonth(); ok {
		_spec.AddField(article.FieldMonth, field.TypeInt, value)
	}
	if value, ok := au.mutation.Day(); ok {
		_spec.SetField(article.FieldDay, field.TypeInt, value)
	}
	if value, ok := au.mutation.AddedDay(); ok {
		_spec.AddField(article.FieldDay, field.TypeInt, value)
	}
	if value, ok := au.mutation.CreatedAt(); ok {
		_spec.SetField(article.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := au.mutation.UpdatedAt(); ok {
		_spec.SetField(article.FieldUpdatedAt, field.TypeTime, value)
	}
	if au.mutation.NewspaperCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   article.NewspaperTable,
			Columns: []string{article.NewspaperColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(newspaper.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.NewspaperIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   article.NewspaperTable,
			Columns: []string{article.NewspaperColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(newspaper.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{article.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// ArticleUpdateOne is the builder for updating a single Article entity.
type ArticleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ArticleMutation
}

// SetContent sets the "content" field.
func (auo *ArticleUpdateOne) SetContent(s string) *ArticleUpdateOne {
	auo.mutation.SetContent(s)
	return auo
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableContent(s *string) *ArticleUpdateOne {
	if s != nil {
		auo.SetContent(*s)
	}
	return auo
}

// SetYear sets the "year" field.
func (auo *ArticleUpdateOne) SetYear(i int) *ArticleUpdateOne {
	auo.mutation.ResetYear()
	auo.mutation.SetYear(i)
	return auo
}

// SetNillableYear sets the "year" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableYear(i *int) *ArticleUpdateOne {
	if i != nil {
		auo.SetYear(*i)
	}
	return auo
}

// AddYear adds i to the "year" field.
func (auo *ArticleUpdateOne) AddYear(i int) *ArticleUpdateOne {
	auo.mutation.AddYear(i)
	return auo
}

// SetMonth sets the "month" field.
func (auo *ArticleUpdateOne) SetMonth(i int) *ArticleUpdateOne {
	auo.mutation.ResetMonth()
	auo.mutation.SetMonth(i)
	return auo
}

// SetNillableMonth sets the "month" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableMonth(i *int) *ArticleUpdateOne {
	if i != nil {
		auo.SetMonth(*i)
	}
	return auo
}

// AddMonth adds i to the "month" field.
func (auo *ArticleUpdateOne) AddMonth(i int) *ArticleUpdateOne {
	auo.mutation.AddMonth(i)
	return auo
}

// SetDay sets the "day" field.
func (auo *ArticleUpdateOne) SetDay(i int) *ArticleUpdateOne {
	auo.mutation.ResetDay()
	auo.mutation.SetDay(i)
	return auo
}

// SetNillableDay sets the "day" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableDay(i *int) *ArticleUpdateOne {
	if i != nil {
		auo.SetDay(*i)
	}
	return auo
}

// AddDay adds i to the "day" field.
func (auo *ArticleUpdateOne) AddDay(i int) *ArticleUpdateOne {
	auo.mutation.AddDay(i)
	return auo
}

// SetCreatedAt sets the "created_at" field.
func (auo *ArticleUpdateOne) SetCreatedAt(t time.Time) *ArticleUpdateOne {
	auo.mutation.SetCreatedAt(t)
	return auo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableCreatedAt(t *time.Time) *ArticleUpdateOne {
	if t != nil {
		auo.SetCreatedAt(*t)
	}
	return auo
}

// SetUpdatedAt sets the "updated_at" field.
func (auo *ArticleUpdateOne) SetUpdatedAt(t time.Time) *ArticleUpdateOne {
	auo.mutation.SetUpdatedAt(t)
	return auo
}

// SetNewspaperID sets the "newspaper" edge to the Newspaper entity by ID.
func (auo *ArticleUpdateOne) SetNewspaperID(id int) *ArticleUpdateOne {
	auo.mutation.SetNewspaperID(id)
	return auo
}

// SetNillableNewspaperID sets the "newspaper" edge to the Newspaper entity by ID if the given value is not nil.
func (auo *ArticleUpdateOne) SetNillableNewspaperID(id *int) *ArticleUpdateOne {
	if id != nil {
		auo = auo.SetNewspaperID(*id)
	}
	return auo
}

// SetNewspaper sets the "newspaper" edge to the Newspaper entity.
func (auo *ArticleUpdateOne) SetNewspaper(n *Newspaper) *ArticleUpdateOne {
	return auo.SetNewspaperID(n.ID)
}

// Mutation returns the ArticleMutation object of the builder.
func (auo *ArticleUpdateOne) Mutation() *ArticleMutation {
	return auo.mutation
}

// ClearNewspaper clears the "newspaper" edge to the Newspaper entity.
func (auo *ArticleUpdateOne) ClearNewspaper() *ArticleUpdateOne {
	auo.mutation.ClearNewspaper()
	return auo
}

// Where appends a list predicates to the ArticleUpdate builder.
func (auo *ArticleUpdateOne) Where(ps ...predicate.Article) *ArticleUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *ArticleUpdateOne) Select(field string, fields ...string) *ArticleUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Article entity.
func (auo *ArticleUpdateOne) Save(ctx context.Context) (*Article, error) {
	auo.defaults()
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *ArticleUpdateOne) SaveX(ctx context.Context) *Article {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *ArticleUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *ArticleUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (auo *ArticleUpdateOne) defaults() {
	if _, ok := auo.mutation.UpdatedAt(); !ok {
		v := article.UpdateDefaultUpdatedAt()
		auo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *ArticleUpdateOne) check() error {
	if v, ok := auo.mutation.Content(); ok {
		if err := article.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Article.content": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Year(); ok {
		if err := article.YearValidator(v); err != nil {
			return &ValidationError{Name: "year", err: fmt.Errorf(`ent: validator failed for field "Article.year": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Month(); ok {
		if err := article.MonthValidator(v); err != nil {
			return &ValidationError{Name: "month", err: fmt.Errorf(`ent: validator failed for field "Article.month": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Day(); ok {
		if err := article.DayValidator(v); err != nil {
			return &ValidationError{Name: "day", err: fmt.Errorf(`ent: validator failed for field "Article.day": %w`, err)}
		}
	}
	return nil
}

func (auo *ArticleUpdateOne) sqlSave(ctx context.Context) (_node *Article, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(article.Table, article.Columns, sqlgraph.NewFieldSpec(article.FieldID, field.TypeInt))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Article.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, article.FieldID)
		for _, f := range fields {
			if !article.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != article.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Content(); ok {
		_spec.SetField(article.FieldContent, field.TypeString, value)
	}
	if value, ok := auo.mutation.Year(); ok {
		_spec.SetField(article.FieldYear, field.TypeInt, value)
	}
	if value, ok := auo.mutation.AddedYear(); ok {
		_spec.AddField(article.FieldYear, field.TypeInt, value)
	}
	if value, ok := auo.mutation.Month(); ok {
		_spec.SetField(article.FieldMonth, field.TypeInt, value)
	}
	if value, ok := auo.mutation.AddedMonth(); ok {
		_spec.AddField(article.FieldMonth, field.TypeInt, value)
	}
	if value, ok := auo.mutation.Day(); ok {
		_spec.SetField(article.FieldDay, field.TypeInt, value)
	}
	if value, ok := auo.mutation.AddedDay(); ok {
		_spec.AddField(article.FieldDay, field.TypeInt, value)
	}
	if value, ok := auo.mutation.CreatedAt(); ok {
		_spec.SetField(article.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := auo.mutation.UpdatedAt(); ok {
		_spec.SetField(article.FieldUpdatedAt, field.TypeTime, value)
	}
	if auo.mutation.NewspaperCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   article.NewspaperTable,
			Columns: []string{article.NewspaperColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(newspaper.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.NewspaperIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   article.NewspaperTable,
			Columns: []string{article.NewspaperColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(newspaper.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Article{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{article.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
