// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/jijimama/newspaper-app/ent/newspaper"
)

// Newspaper is the model entity for the Newspaper schema.
type Newspaper struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// ColumnName holds the value of the "column_name" field.
	ColumnName string `json:"column_name,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NewspaperQuery when eager-loading is set.
	Edges        NewspaperEdges `json:"edges"`
	selectValues sql.SelectValues
}

// NewspaperEdges holds the relations/edges for other nodes in the graph.
type NewspaperEdges struct {
	// Articles holds the value of the articles edge.
	Articles []*Article `json:"articles,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ArticlesOrErr returns the Articles value or an error if the edge
// was not loaded in eager-loading.
func (e NewspaperEdges) ArticlesOrErr() ([]*Article, error) {
	if e.loadedTypes[0] {
		return e.Articles, nil
	}
	return nil, &NotLoadedError{edge: "articles"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Newspaper) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case newspaper.FieldID:
			values[i] = new(sql.NullInt64)
		case newspaper.FieldName, newspaper.FieldColumnName:
			values[i] = new(sql.NullString)
		case newspaper.FieldCreatedAt, newspaper.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Newspaper fields.
func (n *Newspaper) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case newspaper.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			n.ID = int(value.Int64)
		case newspaper.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				n.Name = value.String
			}
		case newspaper.FieldColumnName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field column_name", values[i])
			} else if value.Valid {
				n.ColumnName = value.String
			}
		case newspaper.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				n.CreatedAt = value.Time
			}
		case newspaper.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				n.UpdatedAt = value.Time
			}
		default:
			n.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Newspaper.
// This includes values selected through modifiers, order, etc.
func (n *Newspaper) Value(name string) (ent.Value, error) {
	return n.selectValues.Get(name)
}

// QueryArticles queries the "articles" edge of the Newspaper entity.
func (n *Newspaper) QueryArticles() *ArticleQuery {
	return NewNewspaperClient(n.config).QueryArticles(n)
}

// Update returns a builder for updating this Newspaper.
// Note that you need to call Newspaper.Unwrap() before calling this method if this Newspaper
// was returned from a transaction, and the transaction was committed or rolled back.
func (n *Newspaper) Update() *NewspaperUpdateOne {
	return NewNewspaperClient(n.config).UpdateOne(n)
}

// Unwrap unwraps the Newspaper entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (n *Newspaper) Unwrap() *Newspaper {
	_tx, ok := n.config.driver.(*txDriver)
	if !ok {
		panic("ent: Newspaper is not a transactional entity")
	}
	n.config.driver = _tx.drv
	return n
}

// String implements the fmt.Stringer.
func (n *Newspaper) String() string {
	var builder strings.Builder
	builder.WriteString("Newspaper(")
	builder.WriteString(fmt.Sprintf("id=%v, ", n.ID))
	builder.WriteString("name=")
	builder.WriteString(n.Name)
	builder.WriteString(", ")
	builder.WriteString("column_name=")
	builder.WriteString(n.ColumnName)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(n.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(n.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Newspapers is a parsable slice of Newspaper.
type Newspapers []*Newspaper
