// Code generated by ent, DO NOT EDIT.

package newspaper

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/jijimama/newspaper-app/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldEQ(FieldName, v))
}

// ColumnName applies equality check predicate on the "column_name" field. It's identical to ColumnNameEQ.
func ColumnName(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldEQ(FieldColumnName, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldContainsFold(FieldName, v))
}

// ColumnNameEQ applies the EQ predicate on the "column_name" field.
func ColumnNameEQ(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldEQ(FieldColumnName, v))
}

// ColumnNameNEQ applies the NEQ predicate on the "column_name" field.
func ColumnNameNEQ(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldNEQ(FieldColumnName, v))
}

// ColumnNameIn applies the In predicate on the "column_name" field.
func ColumnNameIn(vs ...string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldIn(FieldColumnName, vs...))
}

// ColumnNameNotIn applies the NotIn predicate on the "column_name" field.
func ColumnNameNotIn(vs ...string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldNotIn(FieldColumnName, vs...))
}

// ColumnNameGT applies the GT predicate on the "column_name" field.
func ColumnNameGT(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldGT(FieldColumnName, v))
}

// ColumnNameGTE applies the GTE predicate on the "column_name" field.
func ColumnNameGTE(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldGTE(FieldColumnName, v))
}

// ColumnNameLT applies the LT predicate on the "column_name" field.
func ColumnNameLT(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldLT(FieldColumnName, v))
}

// ColumnNameLTE applies the LTE predicate on the "column_name" field.
func ColumnNameLTE(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldLTE(FieldColumnName, v))
}

// ColumnNameContains applies the Contains predicate on the "column_name" field.
func ColumnNameContains(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldContains(FieldColumnName, v))
}

// ColumnNameHasPrefix applies the HasPrefix predicate on the "column_name" field.
func ColumnNameHasPrefix(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldHasPrefix(FieldColumnName, v))
}

// ColumnNameHasSuffix applies the HasSuffix predicate on the "column_name" field.
func ColumnNameHasSuffix(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldHasSuffix(FieldColumnName, v))
}

// ColumnNameEqualFold applies the EqualFold predicate on the "column_name" field.
func ColumnNameEqualFold(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldEqualFold(FieldColumnName, v))
}

// ColumnNameContainsFold applies the ContainsFold predicate on the "column_name" field.
func ColumnNameContainsFold(v string) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldContainsFold(FieldColumnName, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Newspaper {
	return predicate.Newspaper(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasArticles applies the HasEdge predicate on the "articles" edge.
func HasArticles() predicate.Newspaper {
	return predicate.Newspaper(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ArticlesTable, ArticlesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasArticlesWith applies the HasEdge predicate on the "articles" edge with a given conditions (other predicates).
func HasArticlesWith(preds ...predicate.Article) predicate.Newspaper {
	return predicate.Newspaper(func(s *sql.Selector) {
		step := newArticlesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Newspaper) predicate.Newspaper {
	return predicate.Newspaper(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Newspaper) predicate.Newspaper {
	return predicate.Newspaper(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Newspaper) predicate.Newspaper {
	return predicate.Newspaper(sql.NotPredicates(p))
}
